Issue-70 - add custom size boxes and functionality to gen
chanr1atwit/AtmosphericBG pull request #87
Opened 2022-07-22 14:47 UTC by salterdatwit

Some of the implementation will need to change when the configuration is implemented, but not by much. For now, get the functionality out.

closes #70

2022-07-22 17:59 UTC, chanr1atwit requested changes

2022-07-22 17:59 UTC, chanr1atwit commented on Controllers/CoreController.py
> +        if len(width) != 0  and len(height) != 0 and \
what is the / for

2022-07-22 18:16 UTC, salterdatwit commented
The / allows for the current line to continue on to the next line, python doesnt allow multi-line statements without it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: chanr1atwit ***@***.***>
Sent: Friday, July 22, 2022 2:00:05 PM
To: chanr1atwit/AtmosphericBG ***@***.***>
Cc: Salter, Devin W. ***@***.***>; Assign ***@***.***>
Subject: Re: [chanr1atwit/AtmosphericBG] Issue-70 - add custom size boxes and functionality to gen (PR #87)


@chanr1atwit requested changes on this pull request.

________________________________

In Controllers/CoreController.py<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchanr1atwit%2FAtmosphericBG%2Fpull%2F87%23discussion_r927880230&data=05%7C01%7Csalterd%40wit.edu%7C84d3772f5b0747ee4c0908da6c0c026e%7C2af16cc576494528bc4d3d9b6f64c066%7C0%7C0%7C637941096136683174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YDy4nsk2zFwQwYJO2m3LKN2xrcHZZg4bpesMPnGKY64%3D&reserved=0>:

> @@ -53,6 +52,15 @@ def getDynamicState(self):
     def setDynamicState(self, state):
         self.photoLibraryController.enableDynamic = state

+    # Set custom dimensions, check if valid
+    def setCustomDims(self, width, height):
+        dims = None
+        # Valid dims
+        if len(width) != 0  and len(height) != 0 and \


what is the / for

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchanr1atwit%2FAtmosphericBG%2Fpull%2F87%23pullrequestreview-1048234756&data=05%7C01%7Csalterd%40wit.edu%7C84d3772f5b0747ee4c0908da6c0c026e%7C2af16cc576494528bc4d3d9b6f64c066%7C0%7C0%7C637941096136683174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b%2Bj%2FyiQgqaYaSPi08gM0uH5kOZK%2BpRL3SVTEZBNGl08%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANDQG5EAJSJBQOVTRYVAX2LVVLOSLANCNFSM54LZ3S2A&data=05%7C01%7Csalterd%40wit.edu%7C84d3772f5b0747ee4c0908da6c0c026e%7C2af16cc576494528bc4d3d9b6f64c066%7C0%7C0%7C637941096136683174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FLURlB%2FvmK8%2F1ZP99vBjFz2SZ7ivxeOlAx%2F7M%2F2yT7A%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-07-23 00:03 UTC, salterdatwit commented on Controllers/CoreController.py
> +        if len(width) != 0  and len(height) != 0 and \
\ allows for multi-line statements

2022-07-23 00:04 UTC, chanr1atwit approved these changes

2022-07-23 00:05 UTC, merged